---
apiVersion: v1
kind: Service
metadata:
  name: webdav
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31790
    protocol: TCP
  selector:
    app: webdav