---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webdav-pvc
  namespace: kube-system
  annotations:
    volume.beta.kubernetes.io/storage-class: "microk8s-hostpath"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi